In [16]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [17]:
df = pd.read_excel("Temporary_data3_-_Copy.xlsx")
df.head()

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0    2    18         1         1         1        1        1        0   
1    1    11         1         1         1        1        1        0   
2    2    16         1         1         1        1        1       10   
3    1    14         1         1         1        0        1        0   
4    1    16         1         1         2        0        1       50   

   NACCTBI  DIABETES  ...   RSUPFR  RSUPFRM  RSUPPAR  RSUPPARM  RSUPTEM  \
0        0         0  ...  27.9038   2.2157  10.3481    1.7014  13.4250   
1        0         0  ...  29.0600   2.6900   9.2500    1.6300  14.8800   
2        0         1  ...  33.0000   2.5400  13.6900    1.5600  16.2300   
3        0         1  ...  31.6800   2.4100   9.6400    1.4500  15.1100   
4        0         0  ...  28.0631   1.9501   9.1125    1.0427  13.3763   

   RSUPTEMM  RSUPMAR  RSUPMARM  RTRTEM  RTRTEMM  
0    1.7419   9.8700    1.6792  0.8906   1.1947  
1    2.3000   7.2700    1.8900  1.3800   2.0300  
2    2.0700  10.1100    1.8400  1.0100   1.5000  
3    1.6400  10.3900    1.8300  0.7400   1.1000  
4    1.6270   7.5844    1.4595  0.6638   0.8527  

[5 rows x 192 columns]

In [29]:
X_train, X_test, y_train, y_test =train_test_split(df,  df["CDRGLOB"], test_size=0.25, random_state=25)
param_grid = {'C': [0.1, 1, 10, 100,],'gamma': [1, 0.1, 0.01, 0.001],'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True)
grid.fit(X_train, y_train)
grid.best_params_
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))


[[137  33   0   0]
 [ 93  24   1   0]
 [ 31   7   0   0]
 [ 10   3   0   0]]
              precision    recall  f1-score   support

           0       0.51      0.81      0.62       170
           1       0.36      0.20      0.26       118
           2       0.00      0.00      0.00        38
           3       0.00      0.00      0.00        13

    accuracy                           0.47       339
   macro avg       0.22      0.25      0.22       339
weighted avg       0.38      0.47      0.40       339



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
param_grid2 = [{
    'min_samples_split':[2, 3, 4],'min_samples_leaf':[2, 3, 4, 5, 6]
}]
grid2 = GridSearchCV(RandomForestClassifier(), param_grid2, refit=True)
grid2.fit(X_train, y_train)
grid2.best_params_
grid_predictions2 = grid2.predict(X_test)
print(confusion_matrix(y_test, grid_predictions2))
print(classification_report(y_test, grid_predictions2))


[[170   0   0   0]
 [  1 117   0   0]
 [  0  20  18   0]
 [  0   2  11   0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       170
           1       0.84      0.99      0.91       118
           2       0.62      0.47      0.54        38
           3       0.00      0.00      0.00        13

    accuracy                           0.90       339
   macro avg       0.61      0.62      0.61       339
weighted avg       0.86      0.90      0.88       339



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
params3 =  {
    'min_samples_leaf': [1, 2, 3],'max_depth': [1, 2, 3]
}
grid3 = GridSearchCV(DecisionTreeClassifier(), params3, refit=True)
grid3.fit(X_train, y_train)
grid.best_params_
grid_predictions3 = grid3.predict(X_test)
print(confusion_matrix(y_test, grid_predictions3))
print(classification_report(y_test, grid_predictions3))


[[170   0   0   0]
 [  0 118   0   0]
 [  0   0  38   0]
 [  0   0   0  13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       170
           1       1.00      1.00      1.00       118
           2       1.00      1.00      1.00        38
           3       1.00      1.00      1.00        13

    accuracy                           1.00       339
   macro avg       1.00      1.00      1.00       339
weighted avg       1.00      1.00      1.00       339

